---
title: "Incerteza do custo de formação e produção com dependência"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Incerteza do custo de formação e produção com dependência}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vet)
library(copula)
```

```{r}
set.seed(123)
N = 10e3

correlacao = 0.7
taxa <- 0.08
ciclo <- 6

preco_madeira <- runif(N, 100, 200)

copula_normal <- normalCopula(param = correlacao, dim = 2)

dist_unif_norm <- mvdc(
  copula = copula_normal,
  margins = c("unif", "norm"),
  paramMargins = list(
    list(min = 10000, max = 14000), # Custo de formação
    list(mean = 240, sd = 50)       # Volume de madeira
  )
)

amostras <- rMvdc(N, dist_unif_norm)
valor_presente_custo <- amostras[ , 1]
volume <- amostras[ , 2]

producao <- volume * preco_madeira
```

```{r}
plot(valor_presente_custo, volume)
```


```{r}
valor_presente_receita <- producao / (1 + taxa)^ciclo
valor_presente_liquido <- valor_presente_receita - valor_presente_custo

summary(valor_presente_liquido)
```

```{r}
valor_esperado_terra <- (valor_presente_liquido * (1 + taxa)^ciclo) / ((1 + taxa)^ciclo - 1)

summary(valor_esperado_terra)
```


```{r}
valor_arrendamento <- valor_esperado_terra * taxa

summary(valor_arrendamento)
```

