---
title: "Dados simulados"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dados simulados}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vet)
library(ggplot2)
library(purrr)
library(dplyr)
library(tidyr)
library(stringr)
library(sn)
library(copula)
```

# Funções

```{r}
ajusta_extremos <- function(x, minimo, maximo) {

  valores_fora_limites <- x < minimo | x > maximo

  x[valores_fora_limites] <- runif(sum(valores_fora_limites), minimo, maximo)

  return(x)
}

convert_param_skew <- function(x) {
  as.numeric(x) %>%
    cp2dp("SN") %>%
    as.list()
}
```

# Setup

```{r}
set.seed(123)

N = 10000
TAXA = 0.10
ROTACAO = 6
```

# Custo de produção

```{r}
CUSTO = 12000

lst_param_custo <- list(
  min = CUSTO * 0.5,
  max = CUSTO * 1.5,
  mean = CUSTO,
  sd = CUSTO * 0.2,
  skew = 0.7
)

tab_custo <- tibble(
  cd_var = "custo",
  nm_var =  "Custo de formação",
  cd_distribuicao = c("unif", "norm", "sn_pos", "sn_neg"),
  nm_distribuicao = c("unif", "norm", "sn", "sn"),
  vl_amostra = list(
      runif(N, lst_param_custo$min, lst_param_custo$max),
      rnorm(N, lst_param_custo$mean, lst_param_custo$sd),
      rsn(N, dp = cp2dp(
        c(
          lst_param_custo$mean,
          lst_param_custo$sd,
          lst_param_custo$skew
        ),
        "SN"
      )),
      rsn(N, dp = cp2dp(
        c(
          lst_param_custo$mean,
          lst_param_custo$sd,
          -lst_param_custo$skew
        ),
        "SN"
      ))
    )
  ) |>
  unnest(vl_amostra) |>
  group_by(cd_distribuicao) |>
  mutate(vl_amostra = ajusta_extremos(vl_amostra, lst_param_custo$min, lst_param_custo$max)) |>
  ungroup()
```

# Produção de madeira

```{r}
PRODUCAO = 240

lst_param_producao <- list(
  min = PRODUCAO * 0.5,
  max = PRODUCAO * 1.5,
  mean = PRODUCAO,
  sd = PRODUCAO * 0.2,
  skew = 0.7
)

tab_producao <- tibble(
  cd_var = "producao",
  nm_var =  "Producao de madeira",
  cd_distribuicao = c("unif", "norm", "sn_pos", "sn_neg"),
  nm_distribuicao = c("unif", "norm", "sn", "sn"),
  vl_amostra = list(
      runif(N, lst_param_producao$min, lst_param_producao$max),
      rnorm(N, lst_param_producao$mean, lst_param_producao$sd),
      rsn(N, dp = cp2dp(
        c(
          lst_param_producao$mean,
          lst_param_producao$sd,
          lst_param_producao$skew
        ),
        "SN"
      )),
      rsn(N, dp = cp2dp(
        c(
          lst_param_producao$mean,
          lst_param_producao$sd,
          -lst_param_producao$skew
        ),
        "SN"
      ))
    )
  ) |>
  unnest(vl_amostra) |>
  group_by(cd_distribuicao) |>
  mutate(vl_amostra = ajusta_extremos(vl_amostra, lst_param_producao$min, lst_param_producao$max)) |>
  ungroup()
```

# Preço da madeira

```{r}
PRECO = 150

lst_param_preco <- list(
  min = PRECO * 0.5,
  max = PRECO * 1.5,
  mean = PRECO,
  sd = PRECO * 0.2,
  skew = 0.7
)

tab_preco <- tibble(
  cd_var = "preco",
  nm_var =  "Preço da madeira",
  cd_distribuicao = c("unif", "norm", "sn_pos", "sn_neg"),
  nm_distribuicao = c("unif", "norm", "sn", "sn"),
  vl_amostra = list(
      runif(N, lst_param_preco$min, lst_param_preco$max),
      rnorm(N, lst_param_preco$mean, lst_param_preco$sd),
      rsn(N, dp = cp2dp(
        c(
          lst_param_preco$mean,
          lst_param_preco$sd,
          lst_param_preco$skew
        ),
        "SN"
      )),
      rsn(N, dp = cp2dp(
        c(
          lst_param_preco$mean,
          lst_param_preco$sd,
          -lst_param_preco$skew
        ),
        "SN"
      ))
    )
  ) |>
  unnest(vl_amostra) |>
  group_by(cd_distribuicao) |>
  mutate(vl_amostra = ajusta_extremos(vl_amostra, lst_param_preco$min, lst_param_preco$max)) |>
  ungroup()

tab_amostra_independente <- bind_rows(
  tab_custo,
  tab_producao,
  tab_preco
)
```

# Dependencia entre custo e produção

```{r}
tab_grid_copula <- expand_grid(
  cd_distribuicao1 = c("unif", "norm", "sn_pos", "sn_neg"),
  cd_distribuicao2 = c("unif", "norm", "sn_pos", "sn_neg")
)

lst_distribuicao_param <- list(
  unif = c("min", "max"),
  norm = c("mean", "sd"),
  sn_pos = c("mean", "sd", "skew"),
  sn_neg = c("mean", "sd", "skew")
)

vec_corr <- seq(0.1, 0.9, 0.2)

lst_amostra_dependente <- map(seq_len(nrow(tab_grid_copula)), ~vector("list", length(vec_corr)))

for (i in seq_len(nrow(tab_grid_copula))) {

  i_margins <-  c(tab_grid_copula$cd_distribuicao1[i], tab_grid_copula$cd_distribuicao2[i])

  i_is_skew <- str_detect(i_margins, "sn")
  i_is_skew_neg <- str_detect(i_margins, "sn_neg")

  i_custo_param <- lst_param_custo[lst_distribuicao_param[[i_margins[1]]]]
  i_producao_param <- lst_param_producao[lst_distribuicao_param[[i_margins[2]]]]

  i_lst_param_margins <- list(i_custo_param, i_producao_param) |>
    map_if(i_is_skew, \(x) as.numeric(x) |> cp2dp("SN") |> as.list()) |>
    map_if(i_is_skew_neg, \(x) { x$alpha <- x$alpha * -1; x})

  for (ii in seq_along(vec_corr)) {

    ii_copula_normal <- normalCopula(param = vec_corr[ii], dim = 2)

    ii_mult_dist_copula <- mvdc(
      copula = ii_copula_normal,
      margins = str_remove(i_margins, "(_pos)|(_neg)"),
      paramMargins = i_lst_param_margins
    )

    ii_samples <- rMvdc(N, ii_mult_dist_copula)

    ii_custo <- ajusta_extremos(ii_samples[ , 1], lst_param_custo$min, lst_param_custo$max)
    ii_producao <- ajusta_extremos(ii_samples[ , 2], lst_param_producao$min, lst_param_producao$max)

    # plot(ii_samples[ , 1], ii_samples[ , 2])

    lst_amostra_dependente[[i]][[ii]] <- bind_rows(
      tibble(
        cd_var = "custo",
        nm_var = "Custo de formação",
        cd_marginais = str_glue("{i_margins[1]} - {i_margins[2]}"),
        vl_correlacao = vec_corr[ii],
        vl_amostra = ii_custo
      ),
      tibble(
        cd_var = "producao",
        nm_var = "Producao de madeira",
        cd_marginais = str_glue("{i_margins[1]} - {i_margins[2]}"),
        vl_correlacao = vec_corr[ii],
        vl_amostra = ii_producao
      )
    )
  }

}

tab_amostra_dependente <- bind_rows(lst_amostra_dependente)
```

# Valor esperado da terra

## Variáveis independentes

```{r}
vec_aux_dist <- tab_amostra_independente |>
  distinct(cd_distribuicao) |>
  pull()

tab_grid_independente <- expand_grid(
  custo = vec_aux_dist,
  producao = vec_aux_dist,
)

lst_vet_independente <- tab_grid_independente %>%
  mutate(vl_vet = NA)

i = 1
for (i in seq_len(nrow(tab_grid_independente))) {

  lst_vet_independente$vl_vet[i] <- vet(
      taxa = TAXA,
      rotacao = ROTACAO,
      vp_custo = tab_amostra_independente |>
        filter(cd_var == "custo", cd_distribuicao == tab_grid_independente$custo[i]) |>
        pull(vl_amostra),
      producao = tab_amostra_independente |>
        filter(cd_var == "producao", cd_distribuicao == tab_grid_independente$producao[i]) |>
        pull(vl_amostra),
      preco_madeira = PRECO
    ) |>
    list()
}

tab_vet_independente <- unnest(lst_vet_independente, vl_vet)
```

## Variáveis dependentes

```{r}
vec_aux_corr <- c("0.1", "0.3", "0.5", "0.7", "0.9")

tab_grid_dependente <- expand_grid(
    custo = vec_aux_dist,
    producao = vec_aux_dist,
    vl_correlacao = vec_aux_corr
  ) |>
  mutate(cd_marginais = paste(custo, producao, sep = " - "))

lst_vet_dependente <- tab_grid_dependente %>%
  mutate(vl_vet = NA)

i = 1
for (i in seq_len(nrow(tab_grid_dependente))) {

    lst_vet_dependente$vl_vet[i] <- vet(
      taxa = TAXA,
      rotacao = ROTACAO,
      vp_custo = tab_amostra_dependente |>
        filter(
          cd_var == "custo",
          cd_marginais == tab_grid_dependente$cd_marginais[i],
          as.character(vl_correlacao) == tab_grid_dependente$vl_correlacao[i]
        ) |>
        pull(vl_amostra),
      producao = tab_amostra_dependente |>
        filter(
          cd_var == "producao",
          cd_marginais == tab_grid_dependente$cd_marginais[i],
          as.character(vl_correlacao) == tab_grid_dependente$vl_correlacao[i]
        ) |>
        pull(vl_amostra),
      preco_madeira = PRECO
    ) |>
    list()
}

tab_vet_dependente <- unnest(lst_vet_dependente, vl_vet)
```

```{r}
tab_amostra_vet_completo <- tab_grid_dependente |>
  left_join(
    tab_vet_dependente |>
      select(-cd_marginais) |>
      group_nest(custo, producao, vl_correlacao, .key = "data_dependente")
  ) |>
  left_join(
    tab_vet_independente |>
      group_nest(custo, producao, .key = "data_independente")
  ) |>
  mutate(
    ks_test = map2(data_dependente, data_independente, ~ks.test(.x$vl_vet, .y$vl_vet)),
    ks_pvalue = map_dbl(ks_test,~.x$p.value),
    pvalue_sig = ks_pvalue > 0.05,
    d = map_dbl(ks_test,~.x$statistic)
  )

tab_amostra_vet <- tab_amostra_vet_completo |>
  select(-data_dependente, -data_independente, -ks_test)
```


# Dataframes 

```{r}
tab_amostra_independente
```

```{r}
tab_amostra_dependente
```

```{r}
tab_amostra_vet
```

