---
title: "Incerteza no preço da madeira"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Incerteza no preço da madeira}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vet)
```

```{r}
set.seed(123)
N = 10e3

taxa <- 0.08
ciclo <- 6
volume <- 240
preco_madeira <- runif(N, 100, 200)

valor_presente_liquido = vector("numeric", length = N)
```

```{r}
for (i in seq_len(N)) {
  
  receita = volume * preco_madeira[i]
  
  tab_fluxo_caixa <- data.frame(
    item = c(
      "Implantação","Manutenção",
      "Manutenção","Manutenção","Manutenção","Manutenção",
      "Manutenção","Venda da madeira em pé"
    ),
    ano = c(0, 1, 2, 3, 4, 5, 6, 6),
    valor = c(-10000, -800, -500, -200, -200, -200, -200, receita)
  ) |>
   transform(valor_presente = (valor) / ((1 + taxa)^ano))

  valor_presente_liquido[i] = sum(tab_fluxo_caixa$valor_presente)
}
```

```{r}
print(summary(valor_presente_liquido))

hist(valor_presente_liquido)
```

```{r}
valor_esperado_terra <- (valor_presente_liquido * (1 + taxa)^ciclo) / ((1 + taxa)^ciclo - 1)

print(summary(valor_esperado_terra))

hist(valor_esperado_terra)
```

```{r}
valor_arrendamento <- valor_esperado_terra * taxa

print(summary(valor_arrendamento))

hist(valor_arrendamento)
```

